language: python
python:
  - "2.7"

before_install: "pip install -r requeriments.txt"

script: "python manage.py test"
  - "coverage run --source+ingreso_pacientes manage.py test ingreso_pacientes"
    
after_script:
  - "coveralls"